apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo-exporter
  labels:
    app: catch-me-service-monitor
spec:
  selector:
    app: catch-me
  ports:
    - port: 3200
      targetPort: 8081
      name: web
      protocol: TCP